{% set name = "semi-ate-master-app" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-master-app-{{ version }}.tar.gz
  sha256: 426b2518053d2f12ed7f111fead4b35c4af72e33aaeacdf0fbe9825d388de162

build:
  number: 0
  noarch: python
  entry_points:
    - launch_master=ate_master_app.launch_master:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.8
    - python
  run:
    - aiohttp ==3.7.4
    - python >=3.8
    - semi-ate-apps-common
    - semi-ate-common
    - semi-ate-plugins
    - transitions
    - xmltodict

test:
  imports:
    - ate_master_app
    - ate_master_app.execution_strategy
  commands:
    - pip check
    - launch_master --help
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-master-app/
  summary: Master application used for steering the control applications in an ATE test environment.
  license: GPL-2.0-only
  license_file: ate_master_app/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot

